---
deployment:
  tasks:
    - export DEPLOYPATH=/home/iyservlk/public_html/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R admin $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R includes $DEPLOYPATH
    - /bin/cp -R uploads $DEPLOYPATH
    - /bin/cp -R storage $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp *.php $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
