<?php
declare(strict_types=1);

/*
 * All public service-page content lives here.
 *
 * The individual service files only set $serviceSlug and load the shared
 * template. This keeps the layout reusable while allowing every service to
 * have complete, unique content.
 */
return [
    'debt-counselling' => [
        'name' => 'Debt Counselling',
        'icon' => 'fa-scale-balanced',
        'summary' => 'Structured debt support designed to help you regain control.',
        'hero_image' => 'debt-counselling.webp',
        'hero_position' => 'center right',
        'hero' => 'A structured route toward manageable repayments',
        'lead' => 'Get professional guidance when monthly commitments have become difficult to manage.',
        'intro_title' => 'Understand your options before making your next move',
        'intro' => [
            'Debt counselling, also known as debt review, is a regulated process intended to help over-indebted consumers restructure monthly repayments into an amount they can reasonably afford.',
            'Our team explains each stage clearly, assesses your circumstances and helps you understand whether this route is appropriate for you. The aim is a realistic repayment path—not a quick promise or another loan.',
        ],
        'quick_title' => 'Support built around your position',
        'quick_points' => [
            'A confidential affordability assessment',
            'A clear explanation of the regulated process',
            'Guidance on the repayment proposal',
            'Ongoing communication and progress support',
        ],
        'feature_title' => 'How the debt-counselling process works',
        'features' => [
            ['Financial assessment', 'Your income, essential living expenses and credit commitments are reviewed confidentially.'],
            ['Suitability review', 'We explain whether debt counselling may be appropriate and discuss the important consequences.'],
            ['Repayment proposal', 'Where suitable, a more affordable repayment proposal is prepared for participating credit providers.'],
            ['Formal process and support', 'The application follows the applicable regulated process, with communication throughout the repayment journey.'],
        ],
        'suitability_title' => 'Debt counselling may be worth discussing if you are',
        'suitability' => [
            'Falling behind on several credit agreements',
            'Using one account or loan to pay another',
            'Unable to cover essential expenses after repayments',
            'Receiving frequent calls or notices from credit providers',
            'Looking for a regulated and structured repayment route',
        ],
        'documents_title' => 'Documents commonly requested',
        'documents_note' => 'The exact list is confirmed after your first conversation.',
        'documents' => [
            'South African ID or valid identification',
            'Recent payslips or other proof of income',
            'Recent bank statements',
            'Statements for credit accounts and loans',
            'A realistic list of monthly household expenses',
            'Relevant letters or notices from credit providers',
        ],
        'outcome_title' => 'Who may benefit',
        'outcome' => 'Debt counselling may be suitable if you are struggling to keep up with several accounts, regularly falling behind, or feeling overwhelmed by creditor contact. Eligibility, repayment terms and the time required depend on your individual circumstances.',
        'faq' => [
            ['Is debt counselling the same as taking a consolidation loan?', 'No. Debt counselling is a regulated debt-relief process and does not give you a new loan. It assesses affordability and may restructure qualifying repayments through the applicable formal process.'],
            ['Can I apply for new credit while under debt review?', 'Consumers under debt review are generally restricted from taking further credit until the process has been completed and the applicable clearance requirements have been met. Your adviser will explain this before you proceed.'],
            ['How long does debt counselling take?', 'There is no single period for everyone. It depends on your total debt, agreed repayments, interest arrangements and whether payments are maintained.'],
            ['Will debt counselling remove all my debt?', 'No. It is designed to make repayment more manageable, not erase valid debt. The goal is to complete the agreed repayment obligations through a structured process.'],
        ],
        'disclaimer' => 'Debt counselling is a regulated process with important legal and credit implications. Eligibility and results cannot be guaranteed. Applicable fees, restrictions and process requirements must be explained before you agree to proceed.',
        'cta_title' => 'Ready to understand your debt options?',
        'cta_text' => 'Request a confidential, no-obligation conversation with our team.',
    ],

    'personal-loans' => [
        'name' => 'Personal Loans',
        'icon' => 'fa-hand-holding-dollar',
        'summary' => 'Responsible lending support for planned and unexpected needs.',
        'hero_image' => 'personal-loans.webp',
        'hero_position' => 'center right',
        'hero' => 'Responsible lending, considered around your circumstances',
        'lead' => 'Speak to a team that values affordability, transparency and informed decisions.',
        'intro_title' => 'Financial support that starts with affordability',
        'intro' => [
            'Unexpected expenses and important life plans can create a need for additional financial support. We help you understand the options available based on your income, affordability and credit profile.',
            'Every application is subject to assessment, applicable lending requirements and the terms of the relevant product provider. You should understand the total cost and monthly impact before accepting an offer.',
        ],
        'quick_title' => 'A responsible application experience',
        'quick_points' => [
            'Affordability considered before borrowing',
            'Clear document and eligibility guidance',
            'Transparent explanation of costs and terms',
            'No promise of guaranteed approval',
        ],
        'feature_title' => 'How a personal-loan enquiry works',
        'features' => [
            ['Initial conversation', 'Tell us what the funds are for, the amount you are considering and your preferred repayment range.'],
            ['Affordability assessment', 'Income, expenses, existing commitments and credit information are assessed as required.'],
            ['Quotation and explanation', 'If an option is available, the instalment, interest, fees and total repayment are explained before acceptance.'],
            ['Decision and next steps', 'A final decision remains subject to approval, verification and the product provider’s applicable terms.'],
        ],
        'suitability_title' => 'A personal loan may be considered when you have',
        'suitability' => [
            'A specific and necessary personal expense',
            'A stable and verifiable source of income',
            'Enough room in your budget for the full instalment',
            'A clear understanding of the total repayment cost',
            'Considered lower-cost alternatives where available',
        ],
        'documents_title' => 'Documents commonly requested',
        'documents_note' => 'Requirements can differ by lender and employment type.',
        'documents' => [
            'South African ID or valid identification',
            'Recent proof of residential address',
            'Recent payslips or proof of income',
            'Recent bank statements',
            'Employment and workplace contact details',
            'Any additional verification requested during assessment',
        ],
        'outcome_title' => 'Make an informed borrowing decision',
        'outcome' => 'The right finance should be affordable and clearly understood. We help you consider the full monthly impact and total repayment cost before moving forward.',
        'faq' => [
            ['Is approval guaranteed?', 'No. Every application is subject to affordability checks, credit assessment, document verification and the applicable provider’s approval criteria.'],
            ['How much can I borrow?', 'The available amount depends on verified income, expenses, current debt commitments, credit information and product limits. Request only what you reasonably need and can afford.'],
            ['Which costs should I check?', 'Review the interest rate, initiation fee, monthly service fee, credit-life cost where applicable, instalment amount and total repayment shown in the quotation.'],
            ['Will applying affect my credit record?', 'A formal application may involve a credit enquiry. The provider should obtain the required consent and explain the assessment process.'],
        ],
        'disclaimer' => 'Personal-loan applications are subject to affordability assessment, credit checks, verification, approval and product terms. Representative examples are not guarantees. Never accept credit before reviewing the full quotation and total repayment obligation.',
        'cta_title' => 'Want to discuss responsible loan options?',
        'cta_text' => 'Contact us for an affordability-focused conversation and clear next steps.',
    ],

    'funeral-cover' => [
        'name' => 'Funeral Cover',
        'icon' => 'fa-dove',
        'summary' => 'Practical cover to help protect your family from funeral costs.',
        'hero_image' => 'funeral-cover.webp',
        'hero_position' => 'center right',
        'hero' => 'Peace of mind for the people who matter most',
        'lead' => 'Prepare for difficult moments with cover suited to your family and budget.',
        'intro_title' => 'Help your family focus on what matters',
        'intro' => [
            'A funeral can create significant costs at short notice. Funeral cover can help reduce that financial pressure and give your family access to support when they need it most.',
            'Our advisers explain available cover levels, premiums, waiting periods, exclusions and the claims process so that you can make a properly informed choice.',
        ],
        'quick_title' => 'Cover explained before commitment',
        'quick_points' => [
            'Cover options for qualifying family members',
            'Premiums considered against your budget',
            'Waiting periods and exclusions explained',
            'Clear beneficiary and claims guidance',
        ],
        'feature_title' => 'How to choose suitable funeral cover',
        'features' => [
            ['Review your household', 'Identify the family members you may need to cover and the likely costs your household would face.'],
            ['Compare cover options', 'Consider benefit amounts, qualifying family members, premiums and any additional services.'],
            ['Understand the policy', 'Review waiting periods, exclusions, premium rules, age limits and the claims requirements.'],
            ['Complete and maintain cover', 'Provide accurate information, nominate beneficiaries where required and keep premiums up to date.'],
        ],
        'suitability_title' => 'Funeral cover may be useful if you want to',
        'suitability' => [
            'Reduce the immediate financial pressure on your family',
            'Provide cover for a spouse, children or qualifying relatives',
            'Choose a benefit level that reflects likely funeral expenses',
            'Pay a predictable premium that fits your monthly budget',
            'Make the claims process clearer for your beneficiaries',
        ],
        'documents_title' => 'Information commonly requested',
        'documents_note' => 'The policy provider will confirm its exact requirements.',
        'documents' => [
            'Policyholder identification and contact details',
            'Identification details for insured family members',
            'Banking or approved premium-payment details',
            'Beneficiary details where applicable',
            'Relationship details for extended-family members',
            'Any health or eligibility information required by the product',
        ],
        'outcome_title' => 'Clarity before commitment',
        'outcome' => 'Benefits, premiums, eligibility and claims requirements differ by product. We help you review the policy information and understand what applies to your household.',
        'faq' => [
            ['What is a waiting period?', 'It is a period after cover starts during which certain claims may not be payable. Waiting periods can differ by cause of death and product, so confirm the exact policy wording.'],
            ['Can I cover extended family members?', 'Some products allow qualifying parents or extended family members to be added. Entry ages, relationships, benefit limits and premiums differ by provider.'],
            ['What happens if a premium is missed?', 'Cover may lapse or be suspended depending on the policy rules and grace period. Contact the provider immediately rather than assuming the policy remains active.'],
            ['What is normally needed for a claim?', 'Requirements may include a claim form, death certificate, identification, beneficiary information and supporting documents. The policy schedule should explain the exact process.'],
        ],
        'disclaimer' => 'Funeral-cover benefits are subject to the policy wording, eligibility, waiting periods, exclusions, premium payment and claims requirements. Always review the policy schedule and disclosures before joining.',
        'cta_title' => 'Protect your family’s peace of mind',
        'cta_text' => 'Talk to an adviser about cover suited to your household and budget.',
    ],

    'legal-insurance' => [
        'name' => 'Legal Insurance',
        'icon' => 'fa-gavel',
        'summary' => 'Affordable access to guidance when legal concerns arise.',
        'hero_image' => 'legal-insurance.webp',
        'hero_position' => 'center right',
        'hero' => 'Support when everyday legal matters become complicated',
        'lead' => 'Understand available legal-cover options before you need to use them.',
        'intro_title' => 'Prepare for unpredictable legal costs',
        'intro' => [
            'Workplace, family, consumer and other legal disputes can be stressful and expensive. Legal insurance may provide access to advice and representation for covered matters.',
            'We help you compare the scope of cover and understand waiting periods, limits and exclusions before you select a product.',
        ],
        'quick_title' => 'Know what support you are buying',
        'quick_points' => [
            'Access to advice for qualifying matters',
            'Potential representation for covered disputes',
            'Policy limits and exclusions explained',
            'Guidance on how to request assistance',
        ],
        'feature_title' => 'How to review legal-cover options',
        'features' => [
            ['Identify likely needs', 'Consider the workplace, family, consumer or other everyday legal risks most relevant to you.'],
            ['Compare the scope', 'Review which advice, document support, negotiation or representation benefits may be included.'],
            ['Check limitations', 'Understand waiting periods, pre-existing matters, exclusions, benefit limits and provider-panel rules.'],
            ['Know how to access help', 'Keep the policy and contact information available and follow the required process before appointing outside representation.'],
        ],
        'suitability_title' => 'Legal insurance may suit people who want',
        'suitability' => [
            'Predictable monthly access to covered legal support',
            'Guidance with qualifying workplace or consumer matters',
            'Help understanding certain agreements or documents',
            'Potential representation for specified covered disputes',
            'A clear first point of contact when a legal issue arises',
        ],
        'documents_title' => 'Information commonly requested',
        'documents_note' => 'Application and claim requirements vary by product.',
        'documents' => [
            'Policyholder identification and contact details',
            'Proof of address where required',
            'Premium-payment information',
            'Details of dependants if the product includes them',
            'Relevant correspondence and contracts for a legal matter',
            'Dates and background information relating to the dispute',
        ],
        'outcome_title' => 'Know what your policy provides',
        'outcome' => 'Legal-insurance benefits differ between providers. Always review the full policy wording, limits, panel arrangements and exclusions for the cover you select.',
        'faq' => [
            ['Are existing legal disputes covered?', 'Pre-existing or already-known matters are commonly excluded, but rules differ by product. Disclose the circumstances and check the policy wording before relying on cover.'],
            ['Does legal insurance pay every legal cost?', 'No. Cover applies only to specified benefits and may have limits, exclusions or approval requirements. Costs incurred without authorisation may not be covered.'],
            ['Can I choose any lawyer?', 'Some policies use a panel or require prior approval. Confirm the lawyer-selection and authorisation rules before appointing someone independently.'],
            ['When can I start using the policy?', 'This depends on the start date and applicable waiting periods. Some advice benefits may be available sooner than representation benefits.'],
        ],
        'disclaimer' => 'This page provides general product information and is not legal advice. Legal-insurance benefits remain subject to the chosen policy’s wording, limits, waiting periods, exclusions and authorisation process.',
        'cta_title' => 'Want to understand legal-cover options?',
        'cta_text' => 'Ask our team for a clear, no-pressure explanation of the available cover.',
    ],

    'credit-clearance' => [
        'name' => 'Credit Clearance',
        'icon' => 'fa-chart-simple',
        'summary' => 'Practical assistance to understand and improve your credit profile.',
        'hero_image' => 'credit-clearance.png',
        'hero_position' => 'center right',
        'hero' => 'Move toward a healthier credit profile with expert guidance',
        'lead' => 'Start with an accurate review of your credit record and realistic next steps.',
        'intro_title' => 'Understand what is affecting your profile',
        'intro' => [
            'Credit information can influence finance applications and other important opportunities. Our process starts by reviewing your credit profile and identifying entries that may require attention.',
            'We explain which information may be disputed or corrected and where settlement, supporting documentation or a formal process may be necessary. Accurate negative information cannot simply be erased.',
        ],
        'quick_title' => 'A realistic, evidence-based approach',
        'quick_points' => [
            'Review information across your credit profile',
            'Identify possible errors or outdated entries',
            'Prepare supporting evidence for valid disputes',
            'Track submissions and practical next steps',
        ],
        'feature_title' => 'How credit-profile assistance works',
        'features' => [
            ['Obtain and review reports', 'Check active accounts, payment history, defaults, judgements, enquiries and personal details.'],
            ['Verify the information', 'Compare listed information with statements, settlement letters and other available evidence.'],
            ['Take the correct action', 'Raise valid disputes or follow the appropriate settlement, rescission or update process where applicable.'],
            ['Monitor the outcome', 'Track responses, retain reference numbers and confirm whether approved corrections appear on later reports.'],
        ],
        'suitability_title' => 'A credit-profile review may help if you need to',
        'suitability' => [
            'Understand why applications may be unsuccessful',
            'Check for incorrect personal or account information',
            'Update accounts that have been settled or paid',
            'Gather evidence for a legitimate credit-bureau dispute',
            'Create realistic steps toward healthier credit behaviour',
        ],
        'documents_title' => 'Documents that may support the review',
        'documents_note' => 'Only documents relevant to your record will be requested.',
        'documents' => [
            'South African ID or valid identification',
            'Proof of address where required',
            'Recent credit reports if already available',
            'Account statements and payment confirmations',
            'Settlement or paid-up letters',
            'Court, rescission or creditor correspondence where applicable',
        ],
        'outcome_title' => 'Responsible support without false promises',
        'outcome' => 'No legitimate service can simply erase accurate credit information. Results depend on the record, evidence, credit-provider response and applicable legal or bureau process.',
        'faq' => [
            ['Can accurate negative information be removed immediately?', 'No. Accurate information is generally retained for the applicable period unless it must be updated following payment, rescission, expiry or another lawful process.'],
            ['Can you guarantee a higher credit score?', 'No. Scores are calculated by credit bureaus using their own models. Correcting errors and improving payment behaviour may help over time, but a particular increase cannot be guaranteed.'],
            ['How long does a dispute take?', 'Timeframes depend on the bureau, credit provider, evidence and type of dispute. Keep all reference numbers and respond promptly if more information is requested.'],
            ['What if an account has already been paid?', 'Provide the settlement or paid-up evidence so the listing can be checked and the correct update process followed. Payment does not always mean every historical entry disappears immediately.'],
        ],
        'disclaimer' => 'Credit-profile results and timeframes cannot be guaranteed. Only inaccurate, outdated or lawfully removable information should be disputed. Accurate information must be handled through the appropriate payment, update or legal process.',
        'cta_title' => 'Start with a credit-profile review',
        'cta_text' => 'Contact us to discuss what may be affecting your record and which documents to prepare.',
    ],

    'financial-assessment' => [
        'name' => 'Financial Assessment',
        'icon' => 'fa-chart-line',
        'summary' => 'A clear review of your finances to support better decisions.',
        'hero_image' => 'financial-assessment.webp',
        'hero_position' => 'center right',
        'hero' => 'Clarity for your next financial decision',
        'lead' => 'Understand your present position before choosing a financial product or solution.',
        'intro_title' => 'A practical picture of where you stand',
        'intro' => [
            'A financial assessment brings your income, expenses, debt and goals into one clear view. It helps identify pressure points and reveals which options may be worth exploring.',
            'Our team focuses on plain-language explanations and practical next steps that reflect your actual circumstances rather than a one-size-fits-all answer.',
        ],
        'quick_title' => 'See the complete monthly picture',
        'quick_points' => [
            'Income and essential expenses reviewed together',
            'Debt commitments placed in context',
            'Short- and long-term goals considered',
            'Practical next steps explained clearly',
        ],
        'feature_title' => 'What the assessment covers',
        'features' => [
            ['Prepare the information', 'Gather reliable income, expense, debt and account information for an accurate discussion.'],
            ['Review monthly cash flow', 'Compare income with essential expenses, discretionary spending and contractual repayments.'],
            ['Identify pressure and priorities', 'Highlight shortfalls, high-cost commitments, risks and goals requiring attention.'],
            ['Build practical next steps', 'Discuss budgeting changes, questions to raise and services that may be relevant to your circumstances.'],
        ],
        'suitability_title' => 'A financial assessment can be useful when you are',
        'suitability' => [
            'Considering a loan or other financial commitment',
            'Struggling to understand where monthly income goes',
            'Experiencing a change in income or household costs',
            'Trying to prioritise debt and essential expenses',
            'Planning a realistic short- or long-term financial goal',
        ],
        'documents_title' => 'Information that improves the assessment',
        'documents_note' => 'Bring what is available—the team can explain any missing items.',
        'documents' => [
            'Recent proof of income',
            'Recent bank statements',
            'A list of essential household expenses',
            'Loan, credit-card and account statements',
            'Insurance and recurring debit-order information',
            'Notes about your immediate concerns and financial goals',
        ],
        'outcome_title' => 'A useful next-step plan',
        'outcome' => 'You receive a clearer understanding of your position, the pressure points to address and the questions to consider before selecting a service, changing your budget or taking on a new commitment.',
        'faq' => [
            ['Is the conversation confidential?', 'Yes. Your personal and financial information should be handled confidentially and used only for the explained assessment and service process.'],
            ['Does an assessment commit me to a product?', 'No. The purpose is to understand your position. You should receive and review the required information before agreeing to any separate product or service.'],
            ['Do I need perfect records before booking?', 'No. Bring the information you have. Missing statements or unclear expenses can be identified during the conversation so that you know what to gather next.'],
            ['Can my spouse or partner join the assessment?', 'Yes, where finances are shared and everyone consents, a joint conversation may provide a more accurate household view.'],
        ],
        'disclaimer' => 'A financial assessment is based on the accuracy and completeness of the information provided. It does not guarantee product approval or a particular financial result. Product-specific advice and disclosures must follow the applicable process.',
        'cta_title' => 'Know where you stand',
        'cta_text' => 'Book a confidential conversation and start with a clearer view of your finances.',
    ],
];
